### ISSUE TITLE
A function named gausfitc0 is missing from the OMEGA7_Naturalfreq.m file

### ISSUE THREAD

**Issue by Halkaer** [necog-UAM/OMEGA-NaturalFrequencies#1]
I am very interested in your method about calculating natural frequency and want to calculate it by myself. But when I read your code, I found a function named `gausfitc0` is missing from the `OMEGA7_Naturalfreq.m` file. I feel very frustrated, because I am just a step away from fully understanding the whole calculation process of natural frequency. Could you supplement the code of this function? Thanks!

**Comment by necog-UAM** [comment]
Thank you very much for your interest and for letting me know that gausfitc0 was missing. It is now available in the subfxs folder. Please, if you notice anything else missing or not working properly, let me know and I will fix it as soon as possible.
Best,
Almudena

**Comment by Halkaer** [comment]
Thank you so much! I have gained a more thorough understanding of this method!
